<?php /** @var $options array */ ?>

<nav>
    <a href="<?= $_SERVER['HTTP_REFERER'] ?>">Назад</a>
</nav>

<form action="/admin/course/activate" method="post">
    <table border="1">
        <tr>
            <td>id</td>
            <td>Курс</td>
            <td>
                <button type="submit">Активировать</button>
            </td>
        </tr>
        <?php foreach ($options['data'] as $course): ?>
            <tr>
                <?php foreach ($course as $value): ?>
                    <td><?= $value ?></td>
                <?php endforeach; ?>
                <td><input type="checkbox" name="<?= $course['id'] ?>" value="<?= $course['id'] ?>"></td>
            </tr>
        <?php endforeach; ?>
    </table>
</form>
