<?php /**
 * @var $options array
 * @var $this \View\TaskView
 */ ?>
<nav>
    <a href="<?= $this->serverData->getReferer() ?>">Назад</a>
</nav>

<form action="/admin/user/approve" method="post">
    <table class="table table-bordered">
        <tr>
            <td>id</td>
            <td>Имя</td>
            <td>Группа</td>
            <td>
                <button type="submit">Подтвердить</button>
            </td>
        </tr>
        <?php foreach ($options['data'] as $task): ?>
            <tr>
                <?php foreach ($task as $value): ?>
                    <td><?= $value ?></td>
                <?php endforeach; ?>
                <td><input type="checkbox" name="<?= $task['id'] ?>" value="<?= $task['id'] ?>"></td>
            </tr>
        <?php endforeach; ?>
    </table>
</form>
