<?php /**
 * @var $options array
 * @var $this \View\DefaultView
 */ ?>

<nav>
    <a href="<?= $this->getRefererUri() ?>">Назад</a>
</nav>

<form action="/admin/task/change" method="post">
    <table class="table table-bordered">
        <tr>
            <td>id</td>
            <td>Исполнитель</td>
            <td>Задание</td>
        </tr>
        <?php foreach ($options['data'] as $task): ?>
            <tr>
                <?php foreach ($task as $value): ?>
                    <td><?= $value ?></td>
                <?php endforeach; ?>
                <td><input type="checkbox" name="<?= $task['id'] ?>" value="<?= $task['id'] ?>"></td>
            </tr>
        <?php endforeach; ?>
    </table>
    <br>
    <label>Новое задание</label>
    <input type="text" name="task">
    <button type="submit">Изменить</button>
</form>
