<?php /** @var $options array */ ?>

<nav>
    <a href="<?= $this->serverData->getReferer() ?>">Назад</a>
</nav>

<form action="/admin/course/changeDescription" method="post">
    <table class="table table-bordered">
        <tr>
            <td>id</td>
            <td>Название</td>
            <td>Описание</td>
            <td>Цена</td>
            <td>статус</td>
            <td>
                <button type="submit">Изменить</button>
            </td>
        </tr>
        <?php foreach ($options['data'] as $course): ?>
            <tr>
                <?php foreach ($course as $key => $value): ?>
                    <td><?= $value ?></td>
                <?php endforeach; ?>
                <td><input type="checkbox" name="<?= $course['id'] ?>" value="<?= $course['id'] ?>"></td>
            </tr>
        <?php endforeach; ?>
    </table>
    <br>
    <label>Описание:</label>
    <input type="text" name="description">
</form>
