<?php /**
 * @var $options array
 * @var $this \View\DefaultView
 */ ?>

<nav>
    <a href="<?= $this->getRefererUri() ?>">Назад</a>
</nav>

<form action="/admin/course/deleteFromFacultativeClaim" method="post">
    <table class="table table-bordered">
        <tr>
            <td>Имя</td>
            <td>Курс</td>
            <td>
                <button type="submit">Отменить</button>
            </td>
        </tr>
        <?php foreach ($options['data'] as $value): ?>
            <tr>
                <td><?= $value['name'] ?></td>
                <td><?= $value['title'] ?></td>
                <td><?= $value['lessons_number'] ?></td>
                <td><input type="checkbox" name="<?= $value['facultative_id'] ?>" value="<?= $value['student_id'] ?>"></td>
                <td><a href="/admin/course/confirmFacultativeClaim/<?= $value['student_id'] ?>/<?= $value['facultative_id'] ?>/<?= $value['lessons_number'] ?>">Подтвердить</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</form>
