<?php /** @var $options array */ ?>
<?php echo isset($errMsg) ? $errMsg : '' ?>
<form action="/admin/task/new" method="post" enctype="multipart/form-data">
    <input type="text" name="created_by" value="<?=($options['user']['id'])?>" hidden>
    <br>
    <label>Исполнитель:</label>
    <select multiple name="executor" required>
        <?php foreach ($options['data'] as $user): ?>
            <option value="<?= $user['id'] ?>"><?= $user['name'] ?></option>
        <?php endforeach; ?>
    </select>
    <br>
    <label>Задание:</label>
    <input name="task" type="text" size="30" required/>
    <br>
    <label>Когда закончится:</label>
    <input name="time_end" type="datetime-local" required/>
    <br>
    <label>Фото к задаче:</label>
    <input name="image" type="file"/>
    <br>
    <button type="submit">Создать</button>
</form>
<br>
<form action="/" method="post">
    <button type="submit">Назад</button>
</form>
