<?php /**
 * @var $options array
 * @var $this \View\TaskView
 */ ?>

<nav>
    <a href="<?= $this->serverData->getReferer() ?>">Назад</a>
    <a href="/admin/task/form/new">Создать</a>
    <a href="/admin/task/form/delete">Удалить</a>
    <a href="/admin/task/form/change">Изменить</a>
    <a href="/admin/task/form/approve">Подтвердить</a>
    <a href="/admin/task/form/restart">Возобновить</a>
    <a href="/task/updateStatus">Обновить</a>
</nav>
<?php echo $options['data']['errMsg'] ?? '' ?>
<table class="table table-bordered">
    <tr>
        <td>id</td>
        <td>Время создания</td>
        <td>Создал</td>
        <td>Исполнитель</td>
        <td>Задание</td>
        <td>статус</td>
        <td>Время начала</td>
        <td>Время окончания</td>
        <td>Комментарий</td>
        <td>Подтверждено кем</td>
        <td>Изображение</td>
    </tr>
    <?php foreach ($options['data']['tasks'] as $task): ?>
        <tr>
            <?php foreach ($task as $key => $value): ?>
                <td><?= $this->renderElement($key, $value) ?></td>
            <?php endforeach; ?>
        </tr>
    <?php endforeach; ?>
</table>
