<form action="/task/deleteTask" method="post">
    <table border="1">
        <tr>
            <td>id</td>
            <td>Время создания</td>
            <td>Создал</td>
            <td>Исполнитель</td>
            <td>Задание</td>
            <td>статус</td>
            <td>Время начала</td>
            <td>Время окончания</td>
            <td>Комментарий</td>
            <td>Подтверждено кем</td>
            <td>Изображение</td>
            <td>
                <button type="submit">Удалить</button>
            </td>
        </tr>
        <?php
        foreach ($options['allTasks'] as $tasks) {
            echo "<tr>";
            foreach ($tasks as $key => $task) {
                echo "<td>" . $task . "</td>";
            }
            if ($_SESSION["login"] == "mother") {
                echo "<td><input type='checkbox' name='" . $tasks['id'] . "' value='" . $tasks['id'] . "'></td>";
            } elseif ($_SESSION["login"] == "Папа") {
                if (mb_strtolower($tasks["executor"], "UTF-8") == "сын" || mb_strtolower($tasks["executor"], "UTF-8") == "дочь") {
                    echo "<td><input type='checkbox' name='" . $tasks['id'] . "' value='" . $tasks['id'] . "'></td>";
                }
                echo "</tr>";
            }
        }
        ?>
    </table>
</form>

<form action="/task/updateTask" method="post">
    <label>Изменить задание:</label>
    <p>
        <select multiple name="id">
            <option disabled>Выберите id задания</option>
            <?php
            if ($_SESSION["login"] == "Мама") {
                foreach ($_SESSION["allTasks"] as $tasks) {
                    echo "<option value='" . $tasks['id'] . "'>" . $tasks['id'] . "</option>";
                }
            } elseif ($_SESSION["login"] == "Папа") {
                foreach ($_SESSION["allTasks"] as $tasks) {
                    if (mb_strtolower($tasks["executor"], "UTF-8") == "сын" || mb_strtolower($tasks["executor"], "UTF-8") == "дочь") {
                        echo "<option value='" . $tasks['id'] . "'>" . $tasks['id'] . "</option>";
                    }
                }
            }
            ?>
        </select>
    </p>
    <input name="task" type="text" size="30"/>
    <input type="submit" value="Отправить">

</form>
