<form action='/user/delete' method='post'>
    <table border='1'>
        <tr>
            <td>id</td>
            <td>Имя</td>
            <td>Член семьи</td>
            <td>Возраст</td>
            <td>Адрес</td>
            <td>Статус</td>
            <td>Изображение</td>
            <td>
                <button type='submit'>Удалить</button>
            </td>
        </tr>

        <?php foreach ($options['allUsers'] as $users): ?>
            <tr>
                <?php foreach ($users as $key => $user): ?>
                    <?php if ($key == 'image'):
                        $user = '<img src=\'/Media/images/users/' . $user . "' width='50' height='50' alt='$user'>";
                    elseif ($key == 'approve_status'):
                        $user = ($user == '1') ? 'подтверждён' : 'не подтверждён';
                    endif; ?>
                    <td> <?= $user ?> </td>
                <?php endforeach;
                if ($options['login'] == 'mother'):?>
                    <td><input type='checkbox' name='<?= $users['id'] ?>' value='<?= $users['id'] ?>'></td>
                <?php elseif ($options['login'] == 'father'):
                    if (mb_strtolower($users['family_member'], 'UTF-8') == 'сын' || mb_strtolower($users['family_member'], 'UTF-8') == 'дочь'): ?>
                        <td><input type='checkbox' name='<?= $users['id'] ?>' value='<?= $users['id'] ?>'></td>
                    <?php endif;
                endif; ?>
            </tr>
        <?php endforeach; ?>
    </table>
</form>

<p>
<form action='/user/updateUser' method='post'>
    <label>Изменить статус пользователя:</label>
    <p>
        <select multiple name='id'>
            <option disabled>Выберите пользователя</option>
            <?php if ($options['login'] == 'mother'):
                foreach ($options['allUsers'] as $users): ?>
                    <option value='<?= $users['id'] ?>'><?= $users['name'] ?> </option>;
                <?php endforeach;
            endif;
            ?>
        </select>
    </p>

    <input name='status' type='text' size='30'/>
    <input type='submit' value='Отправить'>
</form>
</p>

<p>
<form action='/user/approveUser' method='post'>
    <label>Подтвердить пользователя:</label>
    <p>
        <select multiple name='id'>
            <option disabled>Выберите пользователя</option>
            <?php foreach ($options['allUsers'] as $users):
                if ($users['approve_status'] == 0):
                    if ($options['login'] == 'mother'): ?>
                        <option value='<?= $users['id'] ?>'><?= $users['name'] ?> </option>
                    <?php elseif ($options['login'] == 'father'):
                        if (mb_strtolower($users['family_member'], 'UTF-8') == 'сын' || mb_strtolower($users['family_member'], 'UTF-8') == 'дочь'): ?>
                            <option value='<?= $users['id'] ?>'><?= $users['name'] ?> </option>
                        <?php endif;
                    endif;
                endif;
            endforeach; ?>
        </select>
    </p>
    <input type='submit' value='Отправить'>
</form>
</p>