<?php /**
 * @var $options array
 * @var $this \View\TaskView
 */ ?>

<?php echo isset($errMsg) ? $errMsg : '' ?>
<?php if ($options['login'] == 'mother'): ?>
    <p>
    <form action="/task/updateTaskStatus" method="post">
        <button type="submit">Обновить статус заданий</button>
    </form>
    </p>
<?php endif; ?>
<form action="/task/deleteTask" method="post">
    <table border="1">
        <tr>
            <td>id</td>
            <td>Время создания</td>
            <td>Создал</td>
            <td>Исполнитель</td>
            <td>Задание</td>
            <td>статус</td>
            <td>Время начала</td>
            <td>Время окончания</td>
            <td>Комментарий</td>
            <td>Подтверждено кем</td>
            <td>Изображение</td>
            <td>
                <button type="submit">Удалить</button>
            </td>
        </tr>
        <?php foreach ($options['allTasks'] as $task): ?>
            <tr>
                <?php foreach ($task as $key => $value): ?>
                    <?php if ($key == 'family_member'): continue; ?>
                    <?php endif; ?>
                    <td><?= $this->renderTaskElement($key, $value) ?></td>
                <?php endforeach; ?>
                <?php if ($this->renderCheckbox($options['login'], $task['family_member'])): ?>
                    <td><input type="checkbox" name="<?= $task['id'] ?>" value="<?= $task['id'] ?>"></td>
                <?php endif; ?>
            </tr>
        <?php endforeach; ?>
    </table>
</form>
<p>
<form action="/task/updateTask" method="post">
    <label>Изменить задание:</label>
    <p>
        <select multiple name="id">
            <option disabled>Выберите id задания</option>
            <?php foreach ($options['allTasks'] as $task): ?>
                <?php if ($this->renderCheckbox($options['login'], $task['family_member'])): ?>
                    <option value="<?= $task['id'] ?>"><?= $task['id'] ?></option>
                <?php endif; ?>
            <?php endforeach; ?>
        </select>
    </p>
    <input name="task" type="text" size="30"/>
    <input type="submit" value="Отправить">
</form>
</p>
