<?php /**
 * @var $options array
 * @var $this \View\DefaultView
 */ ?>

    <nav>
        <a href="<?= $this->serverData->getReferer() ?>">Назад</a>
    </nav>
<?php if ($options['data']): ?>
    <table class="table table-bordered">
        <tr>
            <td>id</td>
            <td>Имя</td>
        </tr>
        <?php foreach ($options['data'] as $student): ?>
            <tr>
                <td><?= $student['id'] ?></td>
                <td><?= $student['name'] ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php else: ?>
    <h3>На этом курсе нету студентов</h3>
<?php endif; ?>
