<?php /**
 * @var $options array
 * @var $this \View\DefaultView
 */ ?>

<nav>
    <a href="<?= $this->getRefererUri() ?>">Назад</a>
</nav>
<table class="table table-bordered">
    <tr>
        <td>Название</td>
        <td>Описание</td>
        <td>Цена</td>
    </tr>
    <tr>
        <td><?= $options['data']['facultative']['title'] ?></td>
        <td><?= $options['data']['facultative']['description'] ?></td>
        <td><?= $options['data']['facultative']['price'] ?></td>
    </tr>
</table>
<form action="/course/registerToFacultative" method="post">
    <label>Введите количество занятий:</label>
    <input type="hidden" name="facultative_id" value="<?= $options['data']['facultative']['id'] ?>">
    <input type="number" name="lessons_number">
    <button type="submit">Подать заявку</button>
</form>