<?php echo isset($errMsg) ? $errMsg : '' ?>
<table border='1'>
    <tr>
        <td>id</td>
        <td>Время создания</td>
        <td>Создал</td>
        <td>Исполнитель</td>
        <td>Задание</td>
        <td>статус</td>
        <td>Время начала</td>
        <td>Время окончания</td>
        <td>Комментарий</td>
        <td>Подтверждено кем</td>
        <td>Изображение</td>
    </tr>
    <?php foreach ($options['failTasks'] as $tasks): ?>
        <tr>
            <?php foreach ($tasks as $key => $task):
                if ($key == 'image'): ?>
                    <img src='/Media/images/tasks/<?= $task ?>' width='50' height='50' alt='$task'>
                <?php endif; ?>
                <td><?= $task ?></td>
            <?php endforeach; ?>
        </tr>
    <?php endforeach; ?>
</table>

<form action='/task/restartTask' method='post'>
    <label>Возобновить задание:</label>
    <p>
        <select multiple name='id'>
            <option disabled>Выберите id задания</option>
            <?php if ($options['login'] == 'mother'):
                foreach ($options['failTasks'] as $tasks): ?>
                    <option value='<?= $tasks['id'] ?>'><?= $tasks['id'] ?></option>
                <?php endforeach;
            endif; ?>
        </select>
    </p>
    <label>Через сколько закончится:</label>
    <input name='time_end' type='text' size='30'/>
    <br>
    <input type='submit' value='Отправить'>
</form>