<?php /** @var $options array */ ?>
<ul>
    <li><a href="/task/myTasks">Мои задачи</a></li>
    <li><a href="/task/allTasks">Все задачи</a></li>
    <li><a href="/user/avatarForm">Изменить/Удалить аватар</a></li>
    <li><a href="/course/dashboard">Дашборд курсов</a></li>
    <li><a href="/user/logout">Логаут</a></li>
    <?php if (isset($options['user']['access'])): ?>
        <li><a href="/admin">Админ панель</a></li>
    <?php endif; ?>
</ul>
