<div class="header_inner">
    <img src="/Media/images/logos/logo.jpg" width="100" height="100" alt="Наш логотип"/>
    <nav class="nav">
        <a class="nav_link" href="/">Главная</a>
        <a class="nav_link" href="/">Наша семья</a>
        <a class="nav_link" href="/user/authorization">Авторизация</a>
        <a class="nav_link" href="/user/registration">Регистрация</a>
        <a class="nav_link" href="/course/list">Курсы Английского</a>
    </nav>
</div>
