<?php /** @var $options array */ ?>
<?php if (!isset($options['login'])): ?>
    <h1>Добро пожаловать! Авторизируйтесь на сайте или пройдите регистрацию</h1>
    <?php echo $options['errMsg'] ?? '' ?>
    <form action="/user/login" method="post">
        <label>Логин:</label>
        <input name="login" type="text" size="30" required placeholder="Ваш логин"/>
        <br>
        <label>Пароль:</label>
        <input name="password" type="password" size="30" required placeholder="Ваш пароль"/>
        <br>
        <button type="submit">Войти</button>
    </form>

    <form action="/user/registration" method="post">
        <button type="submit">Регистрация</button>
    </form>
<?php endif; ?>
