<?php
?>
<table border="1">
    <tr>
        <td>id</td>
        <td>Время создания</td>
        <td>Создал</td>
        <td>Исполнитель</td>
        <td>Задание</td>
        <td>статус</td>
        <td>Время начала</td>
        <td>Время окончания</td>
        <td>Комментарий</td>
        <td>Подтверждено кем</td>
        <td>Изображение</td>
    </tr>
    <?php foreach ($options['myTasks'] as $tasks): ?>
        <tr>
            <?php foreach ($tasks as $key => $task):
                if ($key == 'image'):
                    $task = '<img src=\'/Media/images/tasks/' . $task . "' width='50' height='50' alt='$task'>";
                endif; ?>
                <td><?= $task ?></td>
            <?php endforeach; ?>
        </tr>
    <?php endforeach; ?>
</table>

<form action="/task/userExecTask" method="post">
    <label>Заявить о выполнении задания:</label>
    <p>
        <select multiple name="id">
            <option disabled>Выберите id задания</option>
            <?php
            foreach ($options['myTasks'] as $tasks): ?>
                <option value="<?= $tasks['id'] ?>"> <?= $tasks['id'] ?></option>
            <?php endforeach; ?>
        </select>
    </p>
    <label>Комментарий(опционально):</label>
    <input name="comment" type="text" size="30"/>
    <input type="submit" value="Отправить">
</form>
