<?php /**
 * @var $options array
 * @var $this \View\TaskView
 */ ?>
<nav>
    <a href="/task/updateStatus">Обновить</a>
    <a href="/task/doneForm">Заявить о выполнении</a>
</nav>
<table border="1">
    <tr>
        <td>id</td>
        <td>Время создания</td>
        <td>Создал</td>
        <td>Исполнитель</td>
        <td>Задание</td>
        <td>статус</td>
        <td>Время начала</td>
        <td>Время окончания</td>
        <td>Комментарий</td>
        <td>Подтверждено кем</td>
        <td>Изображение</td>
    </tr>
    <?php foreach ($options['data'] as $task): ?>
        <tr>
            <?php foreach ($task as $key => $value): ?>
                <td><?= $this->renderElement($key, $value) ?></td>
            <?php endforeach; ?>
        </tr>
    <?php endforeach; ?>
</table>
