<?php /** @var $options array */ ?>

<img src="/Media/images/<?= $options['user']['image'] ?>" alt="avatar" width="150px" height="150px">
<h3>Добро пожаловать <?= $options['user']['name'] ?>!</h3>

<?php if ($options['user']['type'] == 'family'): ?>
    <?php include_once 'family_menu.phtml'; ?>
<?php else: ?>
    <?php include_once 'student_menu.phtml'; ?>
<?php endif; ?>
<?php echo isset($options['errMsg']) ? $options['errMsg'] : '' ?>
<?php if (isset($options['data'])): ?>
    <?php if ($options['user']['type'] == 'family'): ?>
        <?php include_once 'user_tasks.phtml'; ?>
<!--    --><?php //else: include_once 'courses.phtml'; ?>
    <?php endif; ?>
<?php endif; ?>
