<?php
?>

<!DOCTYPE html>
<html>

<head>
    <title>Сайт нашей семьи</title>
    <meta charset="utf-8" />
    <style type="text/css">
        #footer {
            position: fixed; /* Фиксированное положение */
            left: 0; bottom: 0; /* Левый нижний угол */
            padding: 10px; /* Поля вокруг текста */
            width: 100%; /* Ширина слоя */
            text-align: center;
        }
        #header {
            /*position: fixed; !* Фиксированное положение *!*/
            padding: 10px; /* Поля вокруг текста */
            width: 100%; /* Ширина слоя */
            /*text-align: left;*/
        }
    </style>
</head>

<body>

<div id="header">
    <img src="/Media/images/logos/logo.jpg" width="100" height="100" alt="Наш логотип"/>
    <span>Добро пожаловать! Мы - семья Кузиных, и это наш сайт.</span>
</div>

