<form action="/user/createUser" method="post" enctype="multipart/form-data">
    <label>Логин:</label>
    <input name="login" type="text" size="30"/>
    <br>
    <label>Пароль:</label>
    <input name="password" type="password" size="30"/>
    <br>
    <label>Статус:</label>
    <input name="status" type="text" size="30"/>
    <br>
    <label>Возраст:</label>
    <input name="age" type="text" size="30"/>
    <br>
    <label>Адрес:</label>
    <input name="address" type="text" size="30"/>
    <br>
    <label>Фото:</label>
    <input name="imageUser" type="file"/>
    <br>
    <button type="submit">Зарегистрировать</button>
</form>
<form action="/" method="post">
    <button type="submit">Назад</button>
</form>