<?php /** @var $options array */ ?>
<!DOCTYPE html>
<html>

<head>
    <title><?php echo $options['title'] ?></title>
    <link href="/Templates/styles/style.css" rel="stylesheet">
</head>

<body>
<div class="container">
    <div class="header">
        <?php include_once($options['header']) ?>
    </div>
    <div>
        <?php if (isset($options['menu'])) {
            include_once($options['menu']);
        } ?>
        <?php include_once($options['content']) ?>
    </div>
    <div class="footer">
        <?php include_once($options['footer']) ?>
    </div>
</div>
</body>

</html>
