<?php /** @var $options array */ ?>
<!DOCTYPE html>
<html>

<head>
    <title><?php echo $options['title'] ?></title>
    <link href="/Templates/styles/style.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body>
<div class="container">
    <div class="header">
        <?php include_once($options['header']) ?>
    </div>
    <div>
        <?php include_once($options['content']) ?>
    </div>
    <div class="footer">
        <?php include_once($options['footer']) ?>
    </div>
</div>
</body>

</html>
